louis-e/arnis

- src/getData.py
- src/main.py
- src/processData.py
This changes the following:
- Use memory maps instead of memory to store specific data, this majorly improves optimization and solves #16 #8, allowing for way larger cities to be rendered
- Make the `--state` flag optional
- Adds a progress bar for `Calculating layers...` job
- Add `--downloader` flag for specifying which downloader (from the choice of `wget`, `curl` and `requests` (default is requests)
> Major optimization and overhall

- LICENSE
- README.md
This PR changes the project's license from MIT to the GNU General Public License (GPL v3). The shift to GPL v3 ensures that the project remains open-source and that any modifications or redistributions are also open-source under the same terms. This prevents the software from being used in closed-source or commercial products without contributing back to the community. By adopting GPL v3, we aim to foster a more collaborative and transparent development environment.
> Change license from MIT to GNU General Public License (GPL v3)

- .envrc
- .gitignore
- flake/flake.lock
- flake/flake.nix
- src/block_definitions.rs
- src/data_processing.rs
- src/element_processing/buildings.rs
- src/element_processing/mod.rs
- src/element_processing/tourisms.rs
- src/retrieve_data.rs
- src/world_editor.rs
Hi, I'm using clippy to format the code and it seems it affected some of the files I touched, hope it's not a big problem.
- respect building:colour and roof:colour - `get_block_for_color`
- fix parsing height for values containing m suffix
- raise height calculation from `levels * 3` to `levels * 4`
- offset floors by 2 to match with the windows
- simple `information=board` implementation
> my improvements

- src/args.rs
I was running into an issue using this on my city because my min longitude started with a negative sign. There was probably a way to escape this, but I couldn't figure it out, and the fix in the code was pretty straightforward. Hopefully this helps someone else!
P.S. Happy thanksgiving from Canada :3
> Allow hyphen at start of bbox argument

- src/world_editor.rs
WIP as I need to clean up the code and fix the progress bar. It's my bed time, I'll try to get that done tomorrow.
There were two separate problems here.
1. We weren't setting the xPos/zPos chunk data, so the chunks were in the wrong positions.
1. We were only saving modified chunks from the reference MCA file, however we need to save them all (so that we can update all the positions)
Fixes #53 and #38
> fix chunk file in wrong location

- src/data_processing.rs
- src/element_processing/amenities.rs
- src/element_processing/barriers.rs
- src/element_processing/bridges.rs
- src/element_processing/buildings.rs
- src/element_processing/doors.rs
- src/element_processing/highways.rs
- src/element_processing/landuse.rs
- src/element_processing/leisure.rs
- src/element_processing/mod.rs
- src/element_processing/natural.rs
- src/element_processing/railways.rs
- src/element_processing/tourisms.rs
- src/element_processing/water_areas.rs
- src/element_processing/waterways.rs
- src/main.rs
- src/osm_parser.rs
- src/retrieve_data.rs
- src/world_editor.rs
Working on adding rivers. Code works as-is, but it's very slow. Takes about 40 minutes to run on my small city. Have some improvements locally but I haven't pushed them up yet.
This required a bit of refactoring so that we could handle relations. I cleaned up some related code at the same time. And this is also based on my other PRs, so I recommend looking at them first (as some of their code is duplicated in this PR)
Before:
After:
This makes a big difference to how my city looks!
> Wide rivers

- Cargo.toml
- src/block_definitions.rs
- src/data_processing.rs
- src/element_processing/amenities.rs
- src/element_processing/barriers.rs
- src/element_processing/bridges.rs
- src/element_processing/buildings.rs
- src/element_processing/doors.rs
- src/element_processing/highways.rs
- src/element_processing/landuse.rs
- src/element_processing/leisure.rs
- src/element_processing/natural.rs
- src/element_processing/railways.rs
- src/element_processing/tourisms.rs
- src/element_processing/tree.rs
- src/element_processing/water_areas.rs
- src/element_processing/waterways.rs
- src/retrieve_data.rs
- src/world_editor.rs
There is probably more that could be done here, but I'd say this fixes #72 and #63. My city took 40GB of RAM originally, and then 20GB after #74. It now only takes 2-3GB of RAM for the same city.
The main improvement comes from reducing the size of the `Block` struct. It's now only 1 byte long. This has also improved performance a bit.
> Memory improvements

- src/args.rs
- src/osm_parser.rs
Default to a world scale of one block per IRL meter, with a new command line option to change this scale. Closes #49
> allow custom world scales

- src/world_editor.rs
Made a small world change that the MC wiki said was okay (if a section only contains one block we don't need to save `data`). Although MC can handle this fine, it seems that some plugins and utilities can't handle it. Ironically, fastanvil itself can't handle it!
It technically makes worlds a bit smaller but it doesn't seem like a big enough benefit to lose compatibility.
> revert a small world change

- .github/workflows/ci-build.yml
- src/args.rs
- src/bresenham.rs
- src/colors.rs
- src/data_processing.rs
- src/element_processing/amenities.rs
- src/element_processing/buildings.rs
- src/element_processing/tourisms.rs
- src/element_processing/tree.rs
- src/element_processing/water_areas.rs
- src/osm_parser.rs
- src/retrieve_data.rs
- src/version_check.rs
- src/world_editor.rs
Fixes based on clippy lints & rustfmt. I added both of these to CI to enforce them in the future. Clippy especially I find super helpful for becoming a better Rust programmer - it'll often tell me better ways to do whatever I'm trying to do.
There are two lints I didn't touch as they'll be fixed by #77 . Once that's merged I'll rebase this and CI should pass
> Clippy fixes

- src/data_processing.rs
- src/world_editor.rs
- Added `.create(true)` to `File::options()` in `create_region` to ensure the region file is created if it doesn't exist, resolving "file not found" error.
- Replaced `std::fs::copy` with `include_bytes!` macro for in-memory access to `region.template`, simplifying file handling and improving performance.
These changes ensure smoother file creation and handling during world generation.
> Fix region file creation and template writing in create_region function

- Cargo.toml
rfd wasn't building on Linux, since its default features appear to be for Windows. This commit changes them to work on Linux.
> Change rfd features to enable manual builds on Linux.

- Cargo.lock
- src/data_processing.rs
- src/element_processing/buildings.rs
- src/main.rs
- src/osm_parser.rs
Added support for processing multipolygon relations as buildings. Updated generate_world to handle ProcessedRelation elements and added generate_building_from_relation function to handle outer ways. Inner ways are not taken into account yet, could be added in the future if needed. Fixes missing buildings in Minecraft generation.
Fixes https://github.com/louis-e/arnis/issues/112
> Fix: Generate multipolygon buildings from OSM relations

- .github/workflows/ci-build.yml
- .github/workflows/release.yml
This fixes some annoyances I had with the CI scripts
> CI changes/improvements

- .github/workflows/ci-build.yml
- Cargo.lock
- Cargo.toml
This allows the folder picker to work on Linux (at least if xdg-desktop-portal is installed)
Fixes #145
> Linux fixes

- src/main.rs
This fixes the GitHub link in the main window
> Initialize the Tauri shell plugin

- LICENSE
**Summary:**
This pull request proposes changing the project's license from GPL-3.0 to Apache License 2.0. The primary motivation for this change is to address ongoing issues with unauthorized websites and individuals misusing the project's name and branding without proper attribution or permission. The Apache 2.0 license offers additional protections, including a trademark clause that prevents misuse of the project name in a way that could mislead users.
**Reason for the Change:**
We've recently encountered several instances of unauthorized websites falsely presenting themselves as official sources of Arnis. While the GPL-3.0 license ensures the project's openness, it lacks provisions to prevent brand misuse. The Apache 2.0 license requires users to give proper attribution and explicitly …
> License Change from GPL-3.0 to Apache 2.0

- .github/workflows/release.yml
This will allow easier packaging in of the binary version in various linux distros (it compiles it using an ubuntu runner, but i have found that the binary works on arch and probably any glibc distro with xorg)
> Add generic linux binary to releases workflow

- src/main.rs
Makes selecting saves or generating a new one work when minecraft is installed as a flatpak on Linux
> Use Minecraft Flatpak directory if it exists

- src/retrieve_data.rs
As mentioned in #246, Overpass is blocked in Russia. I've added fallback url to local Overpass instance. At the moment, only the most reliable one from Mail.ru. It's only called when the previous attempt fails.
Also removed https://overpass.osm.ch/api/interpreter as it only covers Switzerland, which sometimes resulted in 'API returned no data' error.
Not sure if this PR fixes #246. There may be some other reason, as it should eventually result in a timeout error anyway, and this issue is about infinite loading, and the author says VPN doesn't help. Maybe something preventing request even from being started in the first place.
> Add fallback api urls specifically for Russia

- src/block_definitions.rs
- src/cartesian.rs
- src/data_processing.rs
- src/element_processing/amenities.rs
- src/element_processing/barriers.rs
- src/element_processing/bridges.rs
- src/element_processing/buildings.rs
- src/element_processing/highways.rs
- src/element_processing/landuse.rs
- src/element_processing/leisure.rs
- src/element_processing/natural.rs
- src/element_processing/water_areas.rs
- src/ground.rs
- src/main.rs
- src/osm_parser.rs
- src/world_editor.rs
This is heavily WIP. I'm opening this PR at request of @louis-e - it still needs a ton of work. I'm going to do my best to summarize below, but it's been a few months, so I likely won't remember everything and may make some mistakes.
There are two pieces to this:
1. Take elevation data and turn it into a y-map. **I have not started on this**. For debugging I'm just generating sinewaves. I'm doing this in a modular way though, so it should be pretty easy to swap out.
2. Take the y-map and use it to generate the minecraft map. **This is the part I've been focusing on**. It works reasonably well but there are a ton of edge cases to deal with still. Off the top of my head:
- Rivers! The elevation map should have rivers as the low point, but depending on their resolution and how accurate they …
> [WIP] Elevation

- src/block_definitions.rs
This PR makes the "OAK_LEAVES" Block always have `persistent` set to `true`, so that they don't decay.
Fixes #329
> Make leaves persistent to stop hedges from decaying

- Cargo.toml
- src/main.rs
It looks like these are only GUI dependencies. I still need to test that it compiles, but these give unused warnings when compiling with the gui disabled.
> Remove gui-only deps when building cli

- src/element_processing/landuse.rs
- src/element_processing/leisure.rs
- src/element_processing/natural.rs
- src/element_processing/tree.rs
I'm learning the code base by refactoring small files at a time. Tree generation was not so intimidating, so I started here. 😄 
I intend on reducing repetition in this file, making it easier to comprehend and lessening the chance of making a mistake.
What do you think so far? I want to go even further by reducing each of the match arms, since they all kinda do the same thing. I'll get to it tomorrow.
I would probably recommend reviewing this commit-by-commit, since the overall diff will be large.
> Refactor tree generation

- src/colors.rs
I guess these are new warnings clippy found after an update? 🤷🏼‍♂️ This blocks probably all PRs, so this likely needs to get merged first.
> Fix clippy warnings

- src/block_definitions.rs
- src/data_processing.rs
- src/element_processing/landuse.rs
- src/element_processing/leisure.rs
- src/element_processing/natural.rs
- src/ground.rs
Changes: 
- Increased `MAX_Y` to 319 because it's the new height limit of Minecraft
- Added more entries for the `natural` tag, like bare rock, glaciers and others
- Removed trees from farmlands because trees don't grow randomly in the middle of land that is used for growing crops
- Improved winter mode by replacing water with ice (except rivers) and removing crops from farmlands
- Fixed vertical scaling so that it now matches horizontal scaling
- Replaced 15x15 water grid in farmlands with singular water blocks every 8 blocks
- Reworked generation of upper dirt layer, now there's no dirt under stone, sand and ice
- Removed randomly scattered benches (3 oak log blocks) from parks
> Some improvements for the generation

- src/block_definitions.rs
- src/element_processing/buildings.rs
- src/element_processing/tree.rs
I'm not sure why these were initally functions. I think they are better off as global arrays, since the function would initialize a new vec every time its called, whereas this only initializes it once.
TODO
> Change functions returning vecs to global arrays.

- src/args.rs
This was erroneously set to store false, which means it's impossible to enable the terrain from the cli.
> Set `terrain` arg to store true.

- gui-src/js/main.js
- src/args.rs
- src/bbox.rs
- src/geo_coord.rs
- src/ground.rs
- src/main.rs
- src/osm_parser.rs
- src/retrieve_data.rs
We need a more standardized way to represent bounding boxes, as we kind of just throw the string around and parse it into the four corresponding values when we need to.
Fixes #375
> Formal BBox struct

- gui-src/arnis.desktop
This allows proper packaging of the application for Linux distros
> Add a XDG desktop file

- .github/workflows/ci-build.yml
Right now CI rebuilds from scratch for each step. It takes way longer than it needs to. This action supposedly will cache the build artifacts so they can be re-used each step. 
> [!NOTE]
> Github Copilot made this... so who knows if it actually works.
> CI: Add cache action to preserve build artifacts.

- src/block_definitions.rs
- src/data_processing.rs
- src/element_processing/highways.rs
- src/element_processing/landuse.rs
- src/element_processing/leisure.rs
- src/element_processing/natural.rs
- src/world_editor.rs
Some technical changes:
- Removed precalculation of ground levels for terrain mode, taking it directly from the ground object, because it didn't really improve performance and it took extra memory.
- Unified code for both terrain and flat modes by removing `if ground.elevation_enabled {...} else {...}` so the code is simpler, both modes share the same code now and ground is generated the same way in both modes, also fillground works for the flat mode, which can be useful in the future.
- Removed the spawn platform, it isn't really needed, the player always spawns on solid surface
- Always generate bedrock at MIN_Y
- Refactored the check_for_block() function, because the whitelist and blacklist worked basically the same, both returned true, and it would be hard to process whitelist for …
> Optimize ground generation + new natural elements

- src/block_definitions.rs
- src/element_processing/highways.rs
- src/element_processing/leisure.rs
Hi Louis,
This is my first time contributing to a Rust project. 
I noticed a few things I could add while still learning the Rust syntax.
- Fix 'Mincraft' typo (Code still works the same so not sure what that prefix does) 
- Add additional types for leisure
-  I tested this on an ice rink, but it still generated the normal building over it. Ice-rink generation may need to be moved to buildings.rs   
- Will test slipway and nature reserve
- Add additional types for highway
> Update leisure and highway element processing

- Cargo.lock
- Cargo.toml
- src/args.rs
- src/bbox.rs
- src/gui.rs
- src/main.rs
- src/retrieve_data.rs
- src/test_utilities.rs
Just some papercuts I noticed while trying out the CLI:
* `args.run()` is an unfortunate place to do argument validation; can just as well do it while parsing.
* I messed up my bbox the first time around and got an unhelpful error. No more!
* It's useful to be able to always choose to save the Overpass data to a file, instead of only when happening to use `--debug`, so that's now a thing (`--save-json-file`).
> Small data retrieval improvements

- src/retrieve_data.rs
error: this can be `std::io::Error::other(_)`
--> src/retrieve_data.rs:62:13
|
62 |         Err(io::Error::new(io::ErrorKind::Other, "Curl command failed"))
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#io_other_error
= note: `-D clippy::io-other-error` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::io_other_error)]`
help: use `std::io::Error::other`
|
62 -         Err(io::Error::new(io::ErrorKind::Other, "Curl command failed"))
62 +         Err(io::Error::other("Curl command failed"))
|
error: this can be `std::io::Error::other(_)`
--> src/retrieve_data.rs:76:13
|
76 |         Err(io::Error::new(io::ErrorKind::Other, "Wget command …
> Fix clippy

- src/gui.rs
- src/main.rs
- src/osm_parser.rs
- src/test_utilities.rs
* Makes `parse_osm_data` take ownership of the raw data instead of the caller cloning it. IOW, the parser function transmutes the raw data to the parsed stuff.
* Similarly, `SplitOsmData` now does the work of splitting the elements by type, so the loops that handle them don't need to check for types themselves (and also can work without references, on the data itself.) (Future work could improve things there for less cloning.)
* Makes writing the debug file use a buffered writer, which makes it much, much faster.
> Data parsing fixes

- Cargo.toml
- src/element_processing/amenities.rs
- src/element_processing/water_areas.rs
I tried Arnis with a large area that was painfully slow on `--debug`, and would just hang on `--release`.
I mustered enough patience to wait for `--debug` to do its thing, only to see it panic on a overflow.
This PR fixes two of the overflow panics I found, and also turns on `overflow-checks` in release builds so they won't hang in similar situations.
> Some overflow fixes

- .github/workflows/pr-benchmark.yml
Timing `cargo run` means also timing the build if one doesn't exist.
This splits the benchmark CI to build first, then just time the compiled binary.
A follow-up could be to use https://github.com/sharkdp/hyperfine so the benchmark is run a couple of times, but then you'd need to take into account how many times Hyperfine decides to run the benchmark, which is not something I want to implement in Bash math.
I adjusted the baseline duration accordingly in this PR.
> CI: fix benchmark time to not include build
