louis-e/arnis

src/main.py
Implementation by [amir16yp](https://github.com/amir16yp) in https://github.com/louis-e/arnis/issues/44
=> Added validation for bbox input

Cargo.lock, Cargo.toml, README.md, src/args.rs, src/block_definitions.rs, src/data_processing.rs, src/main.rs, src/world_editor.rs
- Modularization: Separated core logic into dedicated modules (world_editor, args, data_processing, block_definitions) for better maintainability.
- Bresenham Algorithm: Implemented efficient block placement for drawing lines in 3D space.
- Block Definitions: Centralized block constants for cleaner and reusable block references.
- Input Argument Parsing: Integrated clap for robust command-line argument handling, including dynamic path and bounding box inputs.
- File Structure: Refined file organization to support scalability and easier navigation.
=> Enhanced modularization and core feature porting

Cargo.toml, src/args.rs, src/block_definitions.rs, src/colors.rs, src/data_processing.rs, src/element_processing/amenities.rs, src/element_processing/buildings.rs, src/element_processing/highways.rs, src/element_processing/landuse.rs, src/element_processing/leisure.rs, src/element_processing/natural.rs, src/element_processing/tourisms.rs, src/floodfill.rs, src/main.rs
- fix floodfill timeout - didn't test this
- better wall and roof color using color distance
- pitch surface
- enable lto #67
=> another round of my improvements

src/osm_parser.rs, src/world_editor.rs
Functionally this works as intended. Just wondering about code cleanup/best practices, so I'm leaving it as a draft for now. Also, this is based off of #74 so that should be merged first.
Fixes #50
=> Make north point north

Cargo.toml, src/data_processing.rs, src/element_processing/water_areas.rs, src/retrieve_data.rs, src/world_editor.rs
Reduces river generation time from 40 minutes to ~1 minute for my city
=> river performance improvements

Cargo.toml, src/block_definitions.rs, src/data_processing.rs, src/element_processing/amenities.rs, src/element_processing/barriers.rs, src/element_processing/bridges.rs, src/element_processing/buildings.rs, src/element_processing/doors.rs, src/element_processing/highways.rs, src/element_processing/landuse.rs, src/element_processing/leisure.rs, src/element_processing/natural.rs, src/element_processing/railways.rs, src/element_processing/tourisms.rs, src/element_processing/tree.rs, src/element_processing/water_areas.rs, src/element_processing/waterways.rs, src/retrieve_data.rs, src/world_editor.rs
Moves the world up to +65, and generates dirt/stone/bedrock beneath it. Minecraft adds fog when you're low down, so this helps with that.
=> Raise the world

README.md, gui-src/css/styles.css, gui-src/index.html, gui-src/js/main.js, src/main.rs, src/world_editor.rs
=> Added settings menu including scale option and custom bbox input

gui-src/index.html, gui-src/js/main.js, src/args.rs, src/block_definitions.rs, src/data_processing.rs, src/element_processing/amenities.rs, src/element_processing/buildings.rs, src/element_processing/highways.rs, src/element_processing/landuse.rs, src/element_processing/leisure.rs, src/element_processing/natural.rs, src/element_processing/tree.rs, src/main.rs
=> Added winter mode

README.md, gui-src/css/styles.css, gui-src/index.html, gui-src/js/main.js, src/args.rs, src/element_processing/highways.rs, src/floodfill.rs, src/main.rs
=> Add floodfill timeout support

gui-src/index.html, gui-src/js/main.js, src/args.rs, src/data_processing.rs, src/main.rs
=> Added groundlevel parameter to settings

src/main.rs
When selecting 'Select existing world', a custom directory can be selected without the need to have Minecraft installed.
=> Enable generation without having Minecraft installed

src/block_definitions.rs, src/data_processing.rs, src/world_editor.rs
Enables https://github.com/louis-e/arnis/issues/70
=> Added set_sign in world_editor.rs

gui-src/index.html
Closes https://github.com/louis-e/arnis/issues/147
=> Adapted minimum scale value to 0.3

gui-src/js/main.js
Fix logic to make sure that generation cannot be started when no world is selected
=> No world selected fix

src/element_processing/buildings.rs, src/main.rs
Fixes https://github.com/louis-e/arnis/issues/154
=> Fix amenity shelter elements

tauri.conf.json
Fixes https://github.com/louis-e/arnis/issues/156, https://github.com/louis-e/arnis/issues/146, https://github.com/louis-e/arnis/issues/150, https://github.com/louis-e/arnis/issues/161, https://github.com/louis-e/arnis/issues/143
=> Embed bootstrapper

Cargo.lock, src/element_processing/buildings.rs
https://github.com/louis-e/arnis/issues/177
=> Added multi level parking buildings

flake/flake.nix
Adds system dependencies to the flake.nix which were required for builds on NixOS / with Nix
=> Add system dependencies to flake.nix

src/data_processing.rs, src/element_processing/buildings.rs, src/main.rs, src/osm_parser.rs
Fixes https://github.com/louis-e/arnis/issues/222
=> fix: respect building:levels tag from OSM relations

src/element_processing/buildings.rs
https://github.com/louis-e/arnis/issues/196, https://github.com/louis-e/arnis/issues/210
=> Scale adaptive building height

src/element_processing/buildings.rs
Fixes https://github.com/louis-e/arnis/issues/204
=> Support building:min_level tag for elevated building parts

src/element_processing/barriers.rs
=> Ignore barrier=kerb

src/block_definitions.rs, src/element_processing/barriers.rs
Adds support for some barrier and fence types
before/after
=> Support barrier / fence types

gui-src/css/styles.css, gui-src/js/main.js, src/main.rs
=> Miscellaneous fixes

.github/workflows/ci-build.yml
In the future, we will start adding more and more unit tests (or at least, *I* will. 😉)
Time to start ensuring they pass in PRs
=> ci: run cargo test

src/element_processing/landuse.rs, src/element_processing/leisure.rs
Discussion in https://github.com/louis-e/arnis/pull/406
=> Revert improvement

gui-src/locales/fi.json
=> Update Finnish translation

README.md, gui-src/css/styles.css, gui-src/index.html, gui-src/js/main.js, src/args.rs, src/data_processing.rs, src/element_processing/buildings.rs, src/element_processing/highways.rs, src/element_processing/landuse.rs, src/element_processing/leisure.rs, src/element_processing/natural.rs, src/element_processing/tree.rs, src/main.rs
- Removed winter / snow mode as discussed in https://github.com/louis-e/arnis/issues/415 since it only adds complexity in future
=> Remove winter mode as discussed in issues/415

src/data_processing.rs, src/element_processing/landuse.rs, src/element_processing/natural.rs, src/main.rs, src/world_editor.rs
- Fix custom layers being generated over ground level
- Remove relative_to_absolute_y() because there's already get_absolute_y() that serves the same purpose
- Remove unnecessary dirt filling, remove duplication of bedrock line
- Fix crash caused by unicode symbols in place names
=> Fixes for pull/423

src/element_processing/landuse.rs, src/element_processing/natural.rs
Another bunch of improvements to generation of natural objects, now adding some nice wetlands
=> Implement wetlands

.github/workflows/ci-build.yml
* use https://github.com/Swatinem/rust-cache for caching
* don't run formatting checks & clippy thrice
(See https://github.com/akx/arnis/pull/1 for this running in my fork)
=> Small CI fixes

src/osm_parser.rs
https://en.wikipedia.org/wiki/Sutherland%E2%80%93Hodgman_algorithm
=> Implement Sutherland-Hodgman algorithm for element clipping

gui-src/js/bbox.js
See https://github.com/openstreetmap/operations/issues/737
=> Update bbox.js - Use preferred tile.openstreetmap.org URL

src/data_processing.rs, src/element_processing/railways.rs
=> Add rollercoasters

src/floodfill.rs
Reduced timeout checking frequency for better performance.
=> Fix indentation
